Update GHA Docs
depot/docs pull request #93
Opened 2024-11-15 21:00 UTC by KFoster-Marks

2024-11-18 14:47 UTC, kylegalbraith requested changes

2024-11-18 14:47 UTC, kylegalbraith commented on content/github-actions/quickstart.mdx
> +Depot supports a variety of different runner types and sizes depending on your CI job needs, including Intel and Arm runners with up to 64 CPUs, and I/O-optimized runners with local NVMe disks. See t
```suggestion
Depot supports a variety of different runner types and sizes depending on your CI job needs, including Intel and Arm runners with up to 64 CPUs. See the [runner type docs](/docs/github-actions/runner-types) for a full list of available labels.
```

IO runners are replaced by ultra runners, which are the default now.

2024-11-18 14:47 UTC, kylegalbraith commented on content/github-actions/quickstart.mdx
> +###
Is there suppose to be a heading here?

2024-11-20 14:01 UTC, KyleTryon approved these changes

2024-11-20 15:54 UTC, kylegalbraith approved these changes

2024-11-20 16:24 UTC, merged